from google.oauth2 import service_account
from googleapiclient.discovery import build
from core.config import settings

class DriveService:
    def __init__(self):
        self.creds = service_account.Credentials.from_service_account_file(
            settings.GOOGLE_CREDS_PATH, 
            scopes=settings.SCOPES
        )
        # API CLIENT SERVICE
        self.service = build('drive', 'v3', credentials=self.creds)

    def search_files(self, q_parameter: str) -> list:
        """
        Executes the query against the Google Drive API.
        The q_parameter is dynamically generated by our LLM later.
        """
        try:
            # We strictly enforce that it only searches within your shared folder
            folder_constraint = f"'{settings.TARGET_FOLDER_ID}' in parents"
            final_query = f"({q_parameter}) and {folder_constraint}"

            # Execute the API call
            results = self.service.files().list(
                q=final_query,
                spaces='drive',
                fields="nextPageToken, files(id, name, mimeType, webViewLink, createdTime)",
                pageSize=10
            ).execute()
            
            return results.get('files', [])
            
        except Exception as e:
            print(f"An error occurred in Drive API: {e}")
            return []

# Instantiate it once to be used across the app
drive_client = DriveService()